config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :entries, except: [:edit, :destroy]
  devise_for :users

  get 'pages/contact'
  get 'pages/about'
  get 'pages/all_time_responses'
  
  get '/my_page', to: 'pages#my_page'

  get '/not_found', to: 'pages#not_found'

  root 'pages#home'

  get '*path' => redirect('/not_found')

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :entries

  validates :name, presence: true, uniqueness: { case_sensitive: false }


  # validate :email_domain

  # def email_domain
  #   domain = email.split("@").last
  #   if !email.blank?
  #     errors.add(:email, "Invalid Domain") if domain != "mygreenplanet.com"
  #   end
  # end

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    if !current_user.admin?
      redirect_to root_path, notice: "You don't have the permission to view this page."
    else
      @entries = Entry.where("created_at >= ? and created_at <= ?", Time.zone.now.midnight, Time.zone.now.end_of_day)
      @users = User.all  
      @users_with_no_entries = User.includes(:entries).references(:entries).where('entries.id IS NULL')
    end

  end

  def show
    if !current_user.member
      redirect_to root_path, notice: "This is a member only page."
    else 
      if current_user != @entry.user
        redirect_to root_path, notice: "You don't have the permission to view this page."      
      end
    end      
  end

  def new
    if !current_user.member
      redirect_to root_path, notice: "This is a member only page."
    end

    @entry = Entry.new
  end

  def edit
    if !current_user.member
      redirect_to root_path, notice: "This is a member only page."
    end

  end

  def create
    if !current_user.member
      redirect_to root_path, notice: "This is a member only page."
    end

    @entry = Entry.new(entry_params)
    @entry.user = current_user

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Your daily health check response was successfully recorded.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    if !current_user.member
      redirect_to root_path, notice: "This is a member only page."
    end

    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    if !current_user.member
      redirect_to root_path, notice: "This is a member only page."
    end

    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
    end
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, notice: "The page you are looking does not exist."

    end

    def entry_params
      params.require(:entry).permit(:question_one, :question_two, :question_three, :question_four, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def all_time_responses
    @entries = Entry.all
    @users = User.all
  end

  def my_page
    if !current_user.nil?
      @user = current_user
    else
      redirect_to root_path, notice: "Please join or sign in."
    end
  end

  def not_found
    redirect_to root_path, notice: "The page you are looking for does not exist."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= javascript_tag "alert('Caution: You will not be able to edit your response once submitted.')" %>

  <div class="field">
  <h5>1. Are you experiencing any of the following new or worsening symptoms?</h5>
  <ul>
    <li style="font-size: 1rem">Fever or chills</li>
    <li style="font-size: 1rem">Nausea and/or vomitting</li>
    <li style="font-size: 1rem">Cough</li>
    <li style="font-size: 1rem">Sore throat</li>
    <li style="font-size: 1rem">Extreme fatigue or tiredness</li>
    <li style="font-size: 1rem">Body aches</li>
    <li style="font-size: 1rem">Difficulty breathing</li>
    <li style="font-size: 1rem">Loss of appetite</li>
    <li style="font-size: 1rem">Diarrhea</li>
    <li style="font-size: 1rem">Headache</li>
    <li style="font-size: 1rem">Loss of sense of smell or taste</li>
  </ul>
    <div style="font-size: 1.1rem; margin: 12px 0px; text-align: right"">
      <%= form.label :question_one, 'YES',
      style: 'position: relative; vertical-align: middle; bottom: 1px;'
      %>
      
      <%= form.check_box :question_one, {checked: true} %>
      <label for="question-one-no" 
      style="margin-left: 40px; position: relative; vertical-align: middle; bottom: 1px;">
        NO
      </label>
      <input type="checkbox" id="question-one-no">
    </div>
  </div>

<hr>  

  <div class="field">
  <h5>2. Have you travelled outside of Canada, including the United States, within the last 14 days?</h5>
    <div style="font-size: 1.1rem; margin: 12px 0px; text-align: right"">
      <%= form.label :question_two, 'YES',
      style: 'position: relative; vertical-align: middle; bottom: 1px;' %>

      <%= form.check_box :question_two, {checked: true} %>
      <label for="question-two-no"
      style="margin-left: 40px; position: relative; vertical-align: middle; bottom: 1px;">
        NO
      </label>
      <input type="checkbox" id="question-two-no">
    </div>
  </div>

<hr>

  <div class="field">
  <h5>3. Have you been idenfitied as a close contact of a COVID-positive case by Public Health?</h5>
    <div style="font-size: 1.1rem; margin: 12px 0px; text-align: right">
      <%= form.label :question_three, 'YES',
      style: 'position: relative; vertical-align: middle; bottom: 1px;' %>

      <%= form.check_box :question_three, {checked: true} %>

      <label for="question-three-no"
      style="margin-left: 40px; position: relative; vertical-align: middle; bottom: 1px;">
        NO
      </label>
      <input type="checkbox" id="question-three-no">
    </div>
  </div>

<hr>

  <div class="field">
  <h5>4. Have you been told to self-isolate by Public Health?</h5>
    <div style="font-size: 1.1rem; margin: 12px 0px; text-align: right">
      <%= form.label :question_four, 'YES',
      style: 'position: relative; vertical-align: middle; bottom: 1px;' %>

      <%= form.check_box :question_four, {checked: true} %>

      <label for="question-four-no"
      style="margin-left: 40px; position: relative; vertical-align: middle; bottom: 1px;">
        NO
      </label>
      <input type="checkbox" id="question-four-no">
    </div>
  </div>

<hr>

  <div class="actions">
    <%= form.submit "SUBMIT", class: "btn btn-primary" %>
  </div>
<% end %>

<hr>

<p style="font-size: 1rem">If you have answered yes to any of these questions, please do not attend work, contact your direct Supervisor for further direction.</p>

<hr>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daily Health Check Responses</h1>

<p>
  Member(s) who has <em>never</em> recorded a response:
  <% @users_with_no_entries.each do |user| %>
    <%= user.name %>
  <% end %>
</p>

<hr>

<p>
  <span>Black: All members</span>
  <br />
  <span style="color: blue">Blue: Member(s) who have completed daily health check today.</span>
</p>

<p>
<% @users.each do |user| %>
  <%= user.name %>,
<% end %>
<br />
<span style="color: blue">
  <% @entries.each do |e| %>
    <%= e.user.name  %>,
  <% end %>
</span>
</p>

<hr>

<% @entries.each do |entry| %>
  <p style="font-size: 1.1rem; font-weight: bold"><%= entry.user.name %></p>
  <%= entry.created_at.localtime.strftime("%b. %d. %Y. %l:%M %p. %A.") %>
  <% if entry.question_one || entry.question_two || entry.question_three || entry.question_four %>
    <span style="color: red">Answered "YES" to one of the questions.</span>
  <% else %>
    <span>✅</span>
  <% end %>
  <hr>
<% end %>

app/views/entries/new.html.erb
<h4><%= Time.now.localtime.strftime("%A - %H:%M") %></h4>
<h5><%= Time.now.localtime.strftime("%B. %d. %Y") %></h5>

<hr>

<p style="color: red; font-weight: bold; text-transform: uppercase; font-size: 1rem">
    Important: 
    <br/>
    - You will not be able to edit your response once submitted.
    <br />
    - Check only one box.
</p>

<hr>

<%= render 'form', entry: @entry %>

<div style="margin-bottom: 20px">
    <%= link_to 'CANCEL', entries_path, class: "btn btn-danger" %>
</div>

app/views/entries/show.html.erb
<h1>Thank you!</h1>

<hr>

<% if @entry.question_one == true || @entry.question_two == true || @entry.question_three == true || @entry.question_four == true %>
  <h3 style="color: red">WAIT!</h3>
  <h5 style="color: red">You have answered "Yes" to one of the questions.</h5>
  <h5 style="color: red">Please do not attend work.</h5>
  <h5 style="color: red">contact your direct Supervisor for further direction.</h5>
<% else %>
  <h5 style="padding: 15px 0px; color: blue">Please stay safe.</h5>
<% end %>

<hr>

<div>
<br />
<h6>Your responses on <%= Time.now.getlocal.strftime("%B. %d. %Y") %></h6>

<br />

<h6>1. Are you experiencing any of the following new or worsening symptoms?
    <% if @entry.question_one %>
      <span>Yes</span>
    <% else %>
      <span>No</span>
    <% end %>
</h6>
  <ul>
    <li style="font-size: .9rem">Fever or chills</li>
    <li style="font-size: .9rem">Nausea and/or vomitting</li>
    <li style="font-size: .9rem">Cough</li>
    <li style="font-size: .9rem">Sore throat</li>
    <li style="font-size: .9rem">Extreme fatigue or tiredness</li>
    <li style="font-size: .9rem">Body aches</li>
    <li style="font-size: .9rem">Difficulty breathing</li>
    <li style="font-size: .9rem">Loss of appetite</li>
    <li style="font-size: .9rem">Diarrhea</li>
    <li style="font-size: .9rem">Headache</li>
    <li style="font-size: .9rem">Loss of sense of smell or taste</li>
  </ul>


  <hr>

  <h6>2. Are you experiencing any of the following new or worsening symptoms?  
      <% if @entry.question_two %>
        <span>Yes</span>
      <% else %>
        <span>No</span>
      <% end %>
  </h6>

  <hr>

  <h6>3. Have you been idenfitied as a close contact of a COVID-positive case by Public Health?
      <% if @entry.question_three %>
        <span>Yes</span>
      <% else %>
        <span>No</span>
      <% end %>  
  </h6>
  
  <hr>

  <h6>4. Have you been told to self-isolate by Public Health?
      <% if @entry.question_four %>
        <span>Yes</span>
      <% else %>
        <span>No</span>
      <% end %>
  </h6>

</div>

<div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'COVID-19: REPORT', root_path, class: 'navbar-brand' %>

  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>

      <% if current_user.admin? %>
        <li class="nav-item">
          <%= link_to 'Admin Dashboard (NO MOBILE)', admin_dashboard_path, class: 'nav-link' %>
        </li>      
        <li class="nav-item">
          <%= link_to 'Daily responses', entries_path, class: 'nav-link' %>
        </li>      
        <li class="nav-item">
          <%= link_to 'All time responses', pages_all_time_responses_path, class: 'nav-link' %>
        </li>      
      <% end %>

        <li class="nav-item">
          <%= link_to 'Create new entry for today', new_entry_path, class: 'nav-link' %>
        </li>
        
    <% end %>

    <% if !user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Join', new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign in', user_session_path, class: 'nav-link' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'Sign out', destroy_user_session_path, class: 'nav-link', method: :delete %>
      </li>
      <li class="nav-item">
        <%= link_to 'My page', my_page_path, class: 'nav-link' %>
      </li>
    <% end %>
      <li class="nav-item">
        <%= link_to 'About', pages_about_path, class: 'nav-link' %>
      </li>
    
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CovidReport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <div class="container">
 
  <% unless notice.nil? %>
    <p class="notice" style="color: blue; margin-top: 10px"><%= notice %></p>
  <% end %>

  <% unless alert.nil? %>
    <p class="alert" style="color: red; margin-top: 10px"><%= alert %></p>
  <% end %>

      <div style="margin-top: 50px">
          <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>COVID-19:REPORT</h1>
<hr>
<p>This website is brought to you by Steve Kim.</p>
<p>If you find any issues/bugs with the website, please contact Steve Kim immediately.</p>

app/views/pages/all_time_responses.html.erb
<p id="notice"><%= notice %></p>

<h1>All Time Health Check Responses</h1>
<h5>Navigate to "Admin Dashboard (No Mobile)" to view responses by each member.</h5>
<hr>

<% @users.each do |user| %>
    <p><%= user.name  %></p>

    <% user.entries.each do |entry| %>
        <%= entry.created_at.localtime.strftime("%b. %d. %Y. %l:%M %p. %A.") %>
        <% if entry.question_one || entry.question_two || entry.question_three || entry.question_four %>
            <span style="color: red">Answered "YES" to one of the questions.</span>
        <% else %>
            <span>✅</span>
        <% end %>
    <% end %>
<hr>
<% end %>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/home.html.erb
<h1>GREEN PLANET</h1>

<h3>Staff Daily Health Check Questions for BC Public Service Workplaces</h3>

<p>To comply with the Public Health Officer’s orders of November 19,
 2020, all staff entering a workplace within the Province of British 
Columbia must confirm they have completed a daily health check prior 
to entering the workplace. </p>

<p>Based on the Public Health Officer’s orders, daily health checks are only 
to be completed by staff, not clients or the public. Some of these 
questions may sound personal but they are important to help ensure 
the health and safety of everyone in the workplace.</p>

app/views/pages/my_page.html.erb
<h1>Hello, <%= @user.email %></h1>
<hr>

  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted"><%= @user.email %></h6>
    <hr>
    <p class="card-text">Joined on: <%= @user.created_at.localtime.strftime("%m. %d. %Y.") %></p>
  </div>
<hr>

<% if @user.entries.length > 1 %>
  <h4>My daily entries</h4>
<% else %>
  <h4>My daily entry</h4>
<% end %>

<ul class="list-group list-group-flush">
  <% @user.entries.each do |entry| %>
    <li class="list-group-item">
      <div>
          <%= entry.created_at.localtime.strftime("%B. %d. %Y. %l:%M %p") %>
      </div>
    </li>
  <% end %>
</ul>